version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Change to corretto8 if using Java 8
    commands:
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests  # Installs dependencies without running tests

  build:
    commands:
      - echo "Building the application..."
      - mvn package -DskipTests  # Creates the JAR file

  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "Copying artifacts..."

artifacts:
  files:
    - target/*.jar  # Stores the JAR file as an artifact
  discard-paths: yes
